- name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: ./services/product-service
          push: true
          tags: |
            nels0n23/product-service:latest
            nels0n23/product-service:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max